// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// ZgMoments
List ZgMoments(Eigen::MatrixXd X, Eigen::MatrixXd Y);
RcppExport SEXP _AdaptiveRegression_ZgMoments(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(ZgMoments(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// predZg
Eigen::MatrixXd predZg(List res_ZgMoments, Eigen::MatrixXd Xtest, int nvmax);
RcppExport SEXP _AdaptiveRegression_predZg(SEXP res_ZgMomentsSEXP, SEXP XtestSEXP, SEXP nvmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type res_ZgMoments(res_ZgMomentsSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Xtest(XtestSEXP);
    Rcpp::traits::input_parameter< int >::type nvmax(nvmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(predZg(res_ZgMoments, Xtest, nvmax));
    return rcpp_result_gen;
END_RCPP
}
// predZgFinal
Eigen::MatrixXd predZgFinal(List res_ZgMoments, Eigen::MatrixXd Xtest, int nv);
RcppExport SEXP _AdaptiveRegression_predZgFinal(SEXP res_ZgMomentsSEXP, SEXP XtestSEXP, SEXP nvSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type res_ZgMoments(res_ZgMomentsSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Xtest(XtestSEXP);
    Rcpp::traits::input_parameter< int >::type nv(nvSEXP);
    rcpp_result_gen = Rcpp::wrap(predZgFinal(res_ZgMoments, Xtest, nv));
    return rcpp_result_gen;
END_RCPP
}
// CVpredZg
Eigen::MatrixXd CVpredZg(Eigen::MatrixXd X, Eigen::MatrixXd Y, List CVFolds, int nvmax);
RcppExport SEXP _AdaptiveRegression_CVpredZg(SEXP XSEXP, SEXP YSEXP, SEXP CVFoldsSEXP, SEXP nvmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Y(YSEXP);
    Rcpp::traits::input_parameter< List >::type CVFolds(CVFoldsSEXP);
    Rcpp::traits::input_parameter< int >::type nvmax(nvmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(CVpredZg(X, Y, CVFolds, nvmax));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_AdaptiveRegression_ZgMoments", (DL_FUNC) &_AdaptiveRegression_ZgMoments, 2},
    {"_AdaptiveRegression_predZg", (DL_FUNC) &_AdaptiveRegression_predZg, 3},
    {"_AdaptiveRegression_predZgFinal", (DL_FUNC) &_AdaptiveRegression_predZgFinal, 3},
    {"_AdaptiveRegression_CVpredZg", (DL_FUNC) &_AdaptiveRegression_CVpredZg, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_AdaptiveRegression(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
