# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ZgMoments <- function(X, Y) {
    .Call('_AdaptiveRegression_ZgMoments', PACKAGE = 'AdaptiveRegression', X, Y)
}

predZg <- function(res_ZgMoments, Xtest, nvmax) {
    .Call('_AdaptiveRegression_predZg', PACKAGE = 'AdaptiveRegression', res_ZgMoments, Xtest, nvmax)
}

predZgFinal <- function(res_ZgMoments, Xtest, nv) {
    .Call('_AdaptiveRegression_predZgFinal', PACKAGE = 'AdaptiveRegression', res_ZgMoments, Xtest, nv)
}

CVpredZg <- function(X, Y, CVFolds, nvmax) {
    .Call('_AdaptiveRegression_CVpredZg', PACKAGE = 'AdaptiveRegression', X, Y, CVFolds, nvmax)
}

